# 1.8 Linear algebra refresher

In [1]:
import numpy as np

## Vector operations

In [2]:
u = np.array([2,4,5,6])

In [3]:
u

array([2, 4, 5, 6])

In [7]:
2*u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1,0,0,2])

In [5]:
v

array([1, 0, 0, 2])

In [6]:
u + v

array([3, 4, 5, 8])

 ## Vector vector multiplication ( dot product)

In [9]:
u * v

array([ 2,  0,  0, 12])

In [13]:
v.shape

(4,)

In [15]:
u.shape

(4,)

In [67]:
def vect_vect_multiplication(u, v):
    """
    A function that does vector x vector multiplication in the following way:
    1. We verify if both vectors have the same shape. u.shape = (4,) v.shape = (4,)
    2. The for loop sums the element-wise products
    """
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result
    

In [17]:
vect_vect_multiplication(u, v)

np.float64(14.0)

In [18]:
u.dot(v)

np.int64(14)

## Matrix-vector multipication

In [21]:
U = np.array([
    [1, 4, 7, 9],
    [2, 6, 3, 8],
    [3, 4, 0, 4]
])

In [22]:
U

array([[1, 4, 7, 9],
       [2, 6, 3, 8],
       [3, 4, 0, 4]])

In [25]:
U.shape

(3, 4)

In [27]:
def matrix_vector_multiplication(U, v):
    """ 
    1. Check the dimensionality match; the number of columns in the matrix should match the number of rows in the vector.
    2. Initialise the resulting matrix with zeros with the same number of rows as the matrix U.
    3. For each element i in the result vector, we calculate the dot product of element i of matrix U and the vector v.
    """
    assert U.shape[1] == v.shape[0]

    num_rows= U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = U[i].dot(v)

    return result

In [28]:
matrix_vector_multiplication(U, v)

array([19., 18., 11.])

In [29]:
U.dot(v)

array([19, 18, 11])

In [30]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [65]:
def matrix_matrix_multi(U,V):
    
    assert U.shape[1]==V.shape[0]

    num_rows = U.shape[0]

    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:,i]
        Uvi= matrix_vector_multiplication(U, vi)
        result[:,i]= Uvi
    return result


In [66]:
matrix_matrix_multi(U,V)

array([[19., 26., 13.],
       [18., 19., 13.],
       [11.,  9., 10.]])

In [60]:
U.dot(V)

array([[19., 26., 13.],
       [18., 19., 13.],
       [11.,  9., 10.]])

## Identity matrix

In [71]:
I = np.eye(3)

In [72]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [76]:
U

array([[1, 4, 7, 9],
       [2, 6, 3, 8],
       [3, 4, 0, 4]])

In [75]:
I.dot(U)

array([[1., 4., 7., 9.],
       [2., 6., 3., 8.],
       [3., 4., 0., 4.]])

## Matrix inverse

In [77]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [81]:
Vs=V[:3,:]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [87]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [88]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])