# Numpy 

In [1]:
import numpy as np

## Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [5]:
a = [1, 2, 5, 7,10]
type(a)

list

In [6]:
b = np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [7]:
b

array([ 1,  2,  5,  7, 10])

In [8]:
b[3]=6

In [9]:
b

array([ 1,  2,  5,  6, 10])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dementional arrays

In [12]:
# array with 5 rows and 2 columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [14]:
n[1, 1]=8
n

array([[1, 2, 3],
       [4, 8, 6],
       [7, 8, 9]])

In [15]:
n[1]

array([4, 8, 6])

In [16]:
n[:2,1] = [2,5]

In [17]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Randomly Generated Array 

In [18]:
# 2D array with 5 rows and 2 columns
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [19]:
np.random.seed(2)
np.random.randn(5, 2)#normal dist

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [20]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [21]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [22]:
# Add a number to all the elemmts of the array
a + 3

array([3, 4, 5, 6, 7])

In [23]:
# multiplication
a * 7

array([ 0,  7, 14, 21, 28])

In [24]:
b = (10+a)*2
b

array([20, 22, 24, 26, 28])

In [25]:
c = a/b
c

array([0.        , 0.04545455, 0.08333333, 0.11538462, 0.14285714])

## Comparison operations

In [26]:
a >= 2

array([False, False,  True,  True,  True])

In [27]:
a > 2

array([False, False, False,  True,  True])

In [28]:
a < b

array([ True,  True,  True,  True,  True])

In [29]:
b < a

array([False, False, False, False, False])

In [30]:
a<c

array([False, False, False, False, False])

In [31]:
a[a < b]

array([0, 1, 2, 3, 4])

## Summarizing operations

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a.min()

np.int64(0)

In [34]:
a.max()

np.int64(4)

In [35]:
a.mean()

np.float64(2.0)

In [36]:
a.sum()

np.int64(10)

In [37]:
a.std()

np.float64(1.4142135623730951)